# Exploring the numpy array

In the last section, we learned about the numpy library and how it differs from the Python list and standard array.

Here, we will explore other common functionalities the numpy package provides us.

In [155]:
import numpy as np

In [156]:
array = np.arange(20)

### Creating n-dimensional arrays

In [157]:
# we can reshape it into m column and n rows
array = array.reshape(5,4)
print("array with 5 columns and 4 rows:")
print(array)
print("shape = ", array.shape)

# it's now n-dimensional
print("new array type = ", type(array))
print("dimensions: ", array.ndim)

array with 5 columns and 4 rows:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
shape =  (5, 4)
new array type =  <class 'numpy.ndarray'>
dimensions:  2


### Exploring arrays

In [158]:
print('dimension: ', array.ndim)
print('type: ', type(array))
print('data type: ', array.dtype.name)

dimension:  2
type:  <class 'numpy.ndarray'>
data type:  int64


In [159]:
print('number of bytes per item: ', array.itemsize)
print('size of array: ', array.size)

number of bytes per item:  8
size of array:  20


### Initializing arrays

In [160]:
# Turn a Python list into an array
a = np.array([1,2,3,4])
print('array of integers: ', a)

# But note that if the list has multiple data types, they will be converted to the same type
a = np.array([1,3,'cat'])
print('array of strings: ', a)

a = np.array([1,3,3.0])
print('array of floats: ', a)

array of integers:  [1 2 3 4]
array of strings:  ['1' '3' 'cat']
array of floats:  [1. 3. 3.]


In [161]:
# Initialize an array of zeroes with m rows n cols:
print('zeroes 3x2:')
a = np.zeros((3,2))
print(a)

# or ones
print('ones 2x3:')
a = np.ones((2,3))
print(a)

zeroes 3x2:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
ones 2x3:
[[1. 1. 1.]
 [1. 1. 1.]]


In [162]:
# you can initialize an array with uninitialized values
# this can result in anything being in the array!
print('uninitialized:')
a = np.empty((1,4))
print(a)

uninitialized:
[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]]


In [163]:
# you can use range to create sequences
print('5 to 100 in steps of 10:')
a = np.arange(5,100,10)
print(a)

5 to 100 in steps of 10:
[ 5 15 25 35 45 55 65 75 85 95]


In [164]:
# with floating point numbers, it's best to use linspace
# linspace returns a vector of n points between a and b
print('5 points between 0 and 1:')
a = np.linspace(0,1,5)
print(a)

5 points between 0 and 1:
[0.   0.25 0.5  0.75 1.  ]


_observe that to get the fractions of 4, you need to add 1 to n!_

In [165]:
# other ways of initializing include:
print('logspace:')
a = np.logspace(1,100, 3)
print(a)

print('geomspace:') # numbers spaced evenly on a log scale (geometric progression)
a = np.geomspace(1,100, 3)
print(a)

print('mgrid:')
a = np.mgrid[0:5,0:5]
print(a)

print('ogrid:')
a = np.ogrid[-1:1:5j]
print(a)

logspace:
[1.00000000e+001 3.16227766e+050 1.00000000e+100]
geomspace:
[  1.  10. 100.]
mgrid:
[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
ogrid:
[-1.  -0.5  0.   0.5  1. ]


### Working with arrays

a couple neat functions to keep in mind:

In [166]:
array = np.arange(0,25).reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [167]:
print('diagonal:')
print(np.diag(array))
print('indexed diagonal (positive:')
print(np.diag(array, k=1))
print('indexed diagonal (negative):')
print(np.diag(array, k=-1))
print('transform this into a new matrix:')
print(np.diag(np.diag(array)))
print('trace = sum of the diagonals:')
print(np.trace(array))

diagonal:
[ 0  6 12 18 24]
indexed diagonal (positive:
[ 1  7 13 19]
indexed diagonal (negative):
[ 5 11 17 23]
transform this into a new matrix:
[[ 0  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 24]]
trace = sum of the diagonals:
60


In [168]:
# return the upper and lower triangles
print('upper triangle:')
print(np.triu(array))
print('lower triangle:')
print(np.tril(array))

upper triangle:
[[ 0  1  2  3  4]
 [ 0  6  7  8  9]
 [ 0  0 12 13 14]
 [ 0  0  0 18 19]
 [ 0  0  0  0 24]]
lower triangle:
[[ 0  0  0  0  0]
 [ 5  6  0  0  0]
 [10 11 12  0  0]
 [15 16 17 18  0]
 [20 21 22 23 24]]


In [169]:
# create a vandermonde matrix
a = np.array([1,2,3,4,5])
print(np.vander(a,5))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [170]:
# create an identity array
print('identity matrix:')
print(np.identity(5)*1)

# eye is similar, but the diagonal can be offset:
print('eye:')
print(np.eye(5))
print('offset by +1:')
print(np.eye(5,k=2))
print('')

#try offsetting the identity matrix:
print('Offsetting the diagonal:')
try:
    print(np.identity(5, k=1))
    print('Successfully offset the identity matrix!')
except:
    print('Error! Cannot offset the identity matrix!')
print("")

identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
eye:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
offset by +1:
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Offsetting the diagonal:
Error! Cannot offset the identity matrix!

