### Random Sampling

In [2]:
import numpy as np

In [6]:
# generate a random number
np.random.rand()

0.21125756208227486

In [16]:
# seed your randomness so they are reproducible:
np.random.seed(1)

print('After seeding:')
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print()

print('After re-seeding:')
np.random.seed(1)
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())

After seeding:
0.417022004702574
0.7203244934421581
0.00011437481734488664

After re-seeding:
0.417022004702574
0.7203244934421581
0.00011437481734488664


In [33]:
print('random int: ', np.random.randint(1,10))
print('random integers: ', np.random.randint(5,25+3))

random int:  4
random integers:  20


In [34]:
# sample from the continuous uniform distribution
np.random.random_sample()

0.059243201301563464

In [36]:
np.array(np.random.random_sample())*5

2.9653275914902846

In [40]:
# Create an array of random numbers m rows x n cols
np.random.rand(3,4)

array([[0.56591203, 0.61393832, 0.95653566, 0.26097898],
       [0.23101542, 0.53344849, 0.94993814, 0.49305959],
       [0.54060051, 0.7654851 , 0.04534573, 0.13996612]])

In [46]:
# Return random bytes
np.random.bytes(5)

b'\x95x(\x96\xcb'

In [51]:
# Randomly permutate a sequence
sequence = np.arange(9) # array of 0..9
print('random sequence of 0 to 9: ')
print(np.random.permutation(sequence))

print('random 3x3 matrix of 0 to 9: ')
print(np.random.permutation(sequence).reshape(3,3))

random sequence of 0 to 9: 
[3 2 7 5 6 1 8 0 4]
random 3x3 matrix of 0 to 9: 
[[7 0 6]
 [8 5 4]
 [2 1 3]]


In [58]:
# shuffle will shuffle the elements in-place in the first axis of a n-d array
# the contents of sub-arrays remain the same
sequence = np.random.random((3,2))
print('sequence:')
print(sequence)
print('shuffle the sequence:')
print(np.random.shuffle(sequence))

sequence:
[[0.77273915 0.15292982]
 [0.57863393 0.009008  ]
 [0.70904252 0.47064081]]
shuffle the sequence:
None


There are tons of other distributions you can draw random numbers from. See more [here](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html).